export const FETCH_PROJECT_TYPES = 'projectType/FETCH_PROJECT_TYPES'
export const FETCH_PROJECT_TYPES_SUCCESS =
  'projectType/FETCH_PROJECT_TYPES_SUCCESS'

export const ADD_PROJECT_TYPE = 'projectType/ADD_PROJECT_TYPE'
export const UPDATE_PROJECT_TYPE = 'projectType/UPDATE_PROJECT_TYPE'
export const DELETE_PROJECT_TYPE = 'projectType/DELETE_PROJECT_TYPE'
