export const FETCH_INVOICES = 'invoice/FETCH_INVOICES'
export const FETCH_INVOICES_SUCCESS = 'invoice/FETCH_INVOICES_SUCCESS'

export const FETCH_SINGLE_INVOICE = 'invoice/FETCH_SINGLE_INVOICE'
export const FETCH_PROJECT_INVOICES = 'invoice/FETCH_PROJECT_INVOICES'
export const ADD_INVOICE = 'invoice/ADD_INVOICE'
export const UPDATE_INVOICE = 'invoice/UPDATE_INVOICE'
export const DELETE_INVOICE = 'invoice/DELETE_INVOICE'
