export const EMPLOYEE_PASSWORD_FORM = 'employee/EMPLOYEE_PASSWORD_FORM'
export const EMPLOYEE_FORM = 'employee/EMPLOYEE_FORM'

export const FETCH_EMPLOYEES = 'employee/FETCH_EMPLOYEES'
export const FETCH_EMPLOYEES_SUCCESS = 'employee/FETCH_EMPLOYEES_SUCCESS'

export const FETCH_SINGLE_EMPLOYEE = 'employee/FETCH_SINGLE_EMPLOYEE'
export const ADD_EMPLOYEE = 'employee/ADD_EMPLOYEE'
export const UPDATE_EMPLOYEE = 'employee/UPDATE_EMPLOYEE'
export const DELETE_EMPLOYEE = 'employee/DELETE_EMPLOYEE'

export const CHANGE_EMPLOYEE_PASSWORD = 'employee/CHANGE_EMPLOYEE_PASSWORD'
